FROM oven/bun:1

WORKDIR /app

# Copy package.json and package-lock.json (if exists)
COPY package*.json ./

# Install dependencies
RUN bun install

COPY . .
USER bun
EXPOSE 3001

CMD ["bun", "start:dev"]
